service: number-management
frameworkVersion: '3'

provider:
  region: us-east-2
  timeout: 30
  stage: ${opt:stage, 'dev'}
  name: aws
  runtime: nodejs18.x

functions:
  allocateNumber:
    handler: dist/index.allocateNumber
    events:
      - http:
          path: /allocate
          method: POST
          cors: true
  deallocateNumber:
    handler: dist/index.deallocateNumber
    events:
      - http:
          path: /deallocate
          method: POST
          cors: true
  listUsers:
    handler: dist/index.listUsers
    events:
      - http:
          path: /users/{organization_id}
          method: GET
          cors: true
  createOrganization:
    handler: dist/index.createOrganizationHandler
    events:
      - http:
          path: /organizations
          method: POST
          cors: true

custom:
  stage: ${opt:stage, self:provider.stage}
  apiName:
    dev: backend-apidev
  importApiGateway:
    name: ${self:custom.apiName.${self:custom.stage}}
    path: /phone-numbers

plugins:
  - serverless-offline
  - serverless-import-apigateway
